version: '3.9'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save '' --appendonly no
volumes:
  mongo-data:
